#!/usr/bin/env bash
# this script uses ssh to connect to the server ubunto using the ssh private key
cat ~/.ssh/holberton.pub | ssh ubuntu@104.196.66.254 "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >>  ~/.ssh/authorized_keys"
