#!/usr/bin/env bash
# install haproxy and congigure it
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update -y
sudo apt-get -y install haproxy=2.0.\*
STR=$'\n
frontend http_front\n
    \tbind *:80\n
    \tdefault_backend web-backend\n
backend web-backend\n
    \tbalance roundrobin\n
    \tserver 3117-web-01 335.237.115.29:80 \n
    server 3117-web-02  54.234.48.216:80 '
echo "$STR" |sudo tee -a /etc/haproxy/haproxy.cfg
STR1=$'\nENABLED=1'
echo "$STR1" |sudo tee -a /etc/default/haproxy
sudo service haproxy restart
