#!/usr/bin/env bash
# this script transfer a file to my server using the private key
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit   
elif [ $# -eq 3 ]
then
    scp "$1" "$3"@"$2":~/
else
    scp -i "$4" "$1" "$3"@"$2":~/
    
fi

