#!/usr/bin/env bash
#this script install nginx on my server ubuntu with the listening on port 80 and editing the #index file to return "Holberton School"
sudo apt-get  update -y 
sudo apt-get install nginx -y
sudo chmod a+rw /var/www/html/index.nginx-debian.html
echo ' Holberton School ' > /var/www/html/index.nginx-debian.html
sudo service nginx restart

