#!/usr/bin/env bash
#this script allow us to return a string with 404 code
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" |sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo touch /var/www/html/error_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
new_string="server_name _;\nerror_page 404 \/error_404.html;\n"
sudo sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-enabled/default
sudo service nginx restart

