#!/usr/bin/env bash
# install ufw and set configurations
sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable

