#!/usr/bin/env bash
# install ufw and set configurations
sudo apt-get install ufw y
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable

